"""empty message

Revision ID: 874af3092db8
Revises: 1994b5691f72
Create Date: 2023-03-29 19:32:14.709137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874af3092db8'
down_revision = '1994b5691f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follows_followedId_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followedId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_followedId_fkey', 'follows', 'users', ['followedId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
